youtube_api_key = "AIzaSyBLuzIZRaRKshJJkGClpLDrPB55F0ETfVo"
openai_api_key = "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"
