youtube_api_key = "AIzaSyBLuzIZRaRKshJJkGClpLDrPB55F0ETfVo"
openai_api_key = "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"
