youtube_api_key = "AIzaSyBLuzIZRaRKshJJkGClpLDrPB55F0ETfVo"
openai_api_key = "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"
